---
project: IndiaLabs
kind: PIPELINE
name: RK_F5_Delete_EndTo_End
icon: organization,left, is-purple
enabled: true
description: This pipeline removes all objects in F5 and Webservers containers
concurrency: 10
input:
  nodeName: ''
_inputMeta:
  nodeName:
    mandatory: true
    description: Please enter the node name without spaces or special characters
workspace:
  type: DOCKER
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    memory: 512
    cpu: 1.0
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - cleanUp
    - getToken
    - deleteVirtualServer
    - deletePool
    - deleteNode
    tasks:
      cleanUp:
        type: SSH
        ignoreFailure: true
        input:
          script: ./cleanup.sh
          username: cloudadmin
          password: ${var.cloudadmin}
          passphrase: ''
          privatekey: ''
          host: 172.16.40.12
          workingDirectory: ''
          arguments: [
            ]
          environmentVariables: {
            }
          continueOnCommandFailure: false
      getToken:
        type: Pipeline
        input:
          pipeline: RK_F5_Get_Token
          inputProperties: {
            }
      deleteNode:
        type: REST
        input:
          action: delete
          url: https://172.16.40.16/mgmt/tm/ltm/node/${input.nodeName}
          headers:
            Accept: application/json
            Content-Type: application/json
            X-F5-Auth-Token: ${Stage0.getToken.output.outputProperties.token}
          payload: ''
      deleteVirtualServer:
        type: REST
        input:
          action: delete
          url: https://172.16.40.16/mgmt/tm/ltm/virtual/${input.nodeName}_virtualServer
          headers:
            Accept: application/json
            Content-Type: application/json
            X-F5-Auth-Token: ${Stage0.getToken.output.outputProperties.token}
          payload: ''
      deletePool:
        type: REST
        input:
          action: delete
          url: https://172.16.40.16/mgmt/tm/ltm/pool/${input.nodeName}_pool
          headers:
            Accept: application/json
            Content-Type: application/json
            X-F5-Auth-Token: ${Stage0.getToken.output.outputProperties.token}
          payload: ''
